### ISSUE TITLE
Active effects in chat lack strings

### ISSUE THREAD

**Issue by apoapostolov** [CarlosFdez/pf2e-persistent-damage#10]
When the turn starts and the option to publish conditions to chat is launched, the conditions do not have strings

![image](https://user-images.githubusercontent.com/4083812/116241523-a7989280-a76d-11eb-85e0-e938bd031160.png)

**Comment by CarlosFdez** [comment]
I've never seen that feature before. Is that new? Or have I never noticed till now? What happens if they have an effect like bless?

**Comment by CarlosFdez** [comment]
Well, since I've seen nothing more on this, I'll assume its no longer an issue.
