### ISSUE TITLE
PF 1.13.x changed strings and Persistent resolving chat messages need to be fixed

### ISSUE THREAD

**Issue by apoapostolov** [CarlosFdez/pf2e-persistent-damage#11]
Lack strings for damage types

![image](https://user-images.githubusercontent.com/4083812/116241676-d3b41380-a76d-11eb-9ca0-032272636da4.png)

**Comment by CarlosFdez** [comment]
Does that persist if you update? I remember fixing that, and also fixing some of the styling for the "wip sheet" while I was in progress (though I never tested with however you're getting token icons in there).

**Comment by CarlosFdez** [comment]
Gonna assume its working now and close the issue.
