### ISSUE TITLE
How to handle draggable persistent damage on a crit?

### ISSUE THREAD

**Issue by fraserstanton** [CarlosFdez/pf2e-persistent-damage#16]
Just curious if you have any thoughts on how to handle the new draggable persistent damage feature when the player crits? Is there a way we can double the dice applied when you drag it onto the target?

**Comment by CarlosFdez** [comment]
Persistent Damage is not capable of critting, unless you mean the critical failure effect of certain spells. For that you'll need to make a seperate persistent damage inline roll per result.

I could probably allow persistent damage rolls to acquire roll data so that at least upcasting will work, but I'll have to think about how to standardize it.

**Comment by fraserstanton** [comment]
Crit does double persistent damage.
https://2e.aonprd.com/Rules.aspx?ID=704
Most bombs also have the splash trait. When you use a thrown weapon with the splash trait, you don't add your Strength modifier to the damage roll. If an attack with a splash weapon fails, succeeds, or critically succeeds, all creatures within 5 feet of the target (including the target) take the listed splash damage. On a critical failure, the bomb misses entirely, dealing no damage. Add splash damage together with the initial damage against the target before applying the target's resistance or weakness. You don't multiply splash damage on a critical hit.

For example, if you throw a lesser acid flask and hit your target, that creature takes 1 acid damage, 1d6 persistent acid damage, and 1 acid splash damage. All other creatures within 5 feet of it take 1 acid splash damage. **On a critical hit**, the target takes 2 acid damage and **2d6 persistent acid damage**, but the splash damage is still 1. If you miss, the target and all creatures within 5 feet take only 1 splash damage. If you critically fail, no one takes any damage.

**Comment by CarlosFdez** [comment]
Interesting. The strike rules says it doubles, but "doubling" can be either doubling the dice or doubling the result. So a critical hit for persistent damage could be 2*1d6 or 2d6. Guess most forms I've seen are crit specializations which are not doubled.

Regardless, you'll need to make separate effects/inline rolls to drag depending on what happens. I'm working within the limitations of the core system, and chat cards on creation when the text is rendered do not receive any roll data or any information regarding the result of the roll. Its something that has annoyed the data entry team I imagine. I've dug a bit into it out of curiosity too.

**Comment by fraserstanton** [comment]
I am going to add rule elements to the bombs in question so it takes care of this item. It will separate it into "outcome":"success" and "outcome":"criticalSuccess"

**Comment by CarlosFdez** [comment]
That's a good idea! And if the outcome is unknown I believe it'll show both.

I expect eventually core will be expanded so more of that info becomes available to descriptions and roll notes, but that's a ways into the future.
