### ISSUE TITLE
not working after updating to 0.7

### ISSUE THREAD

**Issue by jpmiers** [CarlosFdez/pf2e-persistent-damage#17]
Hi Carlos, After updating to persistent damage 0.7 I'm getting this error when ending the turn for a token with the persistent damage dragged from an inline chat button. It was working fine in 0.6.

![](https://cdn.discordapp.com/attachments/409922954634330122/892185450729599046/unknown.png)
 
If you'd like to reach out for more info Discord: jpmiers#6953

**Comment by CarlosFdez** [comment]
Try reinstalling. That looks like some sort of....corruption. Foundry doesn't validate installations.

**Comment by CarlosFdez** [comment]
That said there is a different issue on the newest release of the core system. Its the preformatted of undefined error. Should be resolved in 2.14.3.

**Comment by jpmiers** [comment]
I think the issue was that I installed the update right after installing a pf2e update that was actually corrupted. I wasn't able to fix it until I got the corrupted pf2 issue resolved, then I uninstalled persistent damage, deleted the lingering persistent damage folder in data/modules and then installed everything like normal and now its working fine. Thanks
