### ISSUE TITLE
Spell Effect: Life Boost and Spell Effect: Lifelink Surge not working

### ISSUE THREAD

**Issue by piper93** [CarlosFdez/pf2e-persistent-damage#20]
The spell effects mentioned above don't work when applied to a token. It seems as though the "@item.level.value * 2" part of the rule element is causing issues. Fast Healing with a numerical value works as expected. I've attached the issue that shows up in the console when the effect is applied.

![image](https://user-images.githubusercontent.com/49284223/148294531-efbedb0b-d336-488b-862b-6730fb4b2569.png)

**Comment by JamzTheMan** [comment]
I just ran into the same issue for fast healing, solved it by changing it to `@item.data.data.level.value * 2`

**Comment by CarlosFdez** [comment]
That will work for now. But next version of the system releasing in a week will allow @item.level as well (but not @item.level.value)
