### ISSUE TITLE
Roll mode overrides "Hide Persistant Damage Rolls" setting

### ISSUE THREAD

**Issue by NikolasTzimoulis** [CarlosFdez/pf2e-persistent-damage#23]
I set persistent damage rolls to "Always Show" yet as long as my roll mode was "Private GM Roll" the persistent damage chat messages were hidden from the players (necessitating right-clicking and selecting "reveal for everyone" after every turn, sometimes multiple times per turn, uphill both ways). If the roll mode is "Public Roll", however, the persistent damage messages appear publicly like normal. This must be a new bug because I remember it working correctly with "Private GM Roll" roll mode not too long ago.
![hidepersistentdamage](https://user-images.githubusercontent.com/380852/155435133-08f6b16e-f822-43ef-859e-7cd2be6f17a3.png)

**Comment by CarlosFdez** [comment]
Closing since I believe this has already been resolved.
