### ISSUE TITLE
"Persistent damage" not localized in chat 

### ISSUE THREAD

**Issue by Eikwerno** [CarlosFdez/pf2e-persistent-damage#24]
Hello! Is there a way to add translation to the module? If so, how could that be provided? Or to pull the existing translations from the core module?
![unknown](https://user-images.githubusercontent.com/9142090/158905065-84770993-180b-4de2-86a4-bc4bdaf7dd47.png)

**Comment by manfred7168** [comment]
Hi I want to give some explanations on this issue. In the german translation of PF2e I set translation of those persistent damages like this:
The bomb deal additional [[/r {1}[persistent,fire]]]{1 Point} @Compendium[pf2e.conditionitems.lDVqvLKA6eF3Df60]{Persistent Fire Damage}.
(I entered english texts for your understanding, of course). When showing in descriptions this works as expected
[* 1 Point] [Persistent Fire Damage]. But when we activate your persistent damage module it breaks showing the above and no localization. Just by inserting a localization of the Roll-Button within {}
I hope this helps analysing.

**Comment by CarlosFdez** [comment]
Ah sorry I just saw this. That's hardcoded, but it should be localized. It won't be a perfect localization (no handling of RTL languages), but it'll be better than before.

**Comment by CarlosFdez** [comment]
Done. Persistent Damage for the effect name should now use the condition name defined in the system, which should be PF2E.condition.persistent-damage.name. Let me know if this resolves the issue. I can't really get german working on my foundry for some reason. The sheets are all broken.

**Comment by Eikwerno** [comment]
Works like a charm as far as I can see. Thank you for the swift action! Much appreciated!
