### ISSUE TITLE
Fast Healing does not automatically heal

### ISSUE THREAD

**Issue by trapbuilder2** [CarlosFdez/pf2e-persistent-damage#28]
Applying the following rule element doesn't cause the target actor to heal, it just puts a number into chat

{"key":"FastHealing","type":"fast-healing","value:1}

**Comment by CarlosFdez** [comment]
FastHealing is core system, this module just provides some effects. But even then, its working as intended, fast healing/persistent damage messages are reminders, and currently don't change hp values.
