### ISSUE TITLE
damage type cannot be selected using the macro

### ISSUE THREAD

**Issue by Sparkasaurusmex** [CarlosFdez/pf2e-persistent-damage#29]
Foundry 10.286 PF2e 4.1.0
Clicking on the damage type doesn't stick, then clicking Add results in "Persistent Damage Errors: Missing damage value"

**Comment by CarlosFdez** [comment]
That's concerning, I tried the macro out myself and it seems to work fine. Can you double check if its due to a module combination, and if so, let me know what that module combination is?

EDIT: And update pf2e as well just to be sure.

**Comment by Sparkasaurusmex** [comment]
Confirmed working in pf2e 4.1.2
