### ISSUE TITLE
issue since upgrade to v10: dialogue box never appears

### ISSUE THREAD

**Issue by dharkus5000** [CarlosFdez/pf2e-persistent-damage#30]
when i used to use this module in foundry v9, when i clicked on the persistent dmg condition/status, i got a dialogue box to let me input a custom amount of dmg and even custom DC, now i just have a condition/status that increases in number as persistent dmg 1, 2, 3 etc - i think this is the default without the module installed?
![image](https://user-images.githubusercontent.com/88220878/193661962-02efa2c1-c97f-466a-84f6-dfd79809c060.png)
the pic shows both the status created by this module (the bottom one), the status created (top one) when clicking the condition in the bottom left, and what the draggable effect dragged to create the status looks like, in the chat at the top, and 2nd from bottom
I have PF2e v4.2.1 and the most recent version of this module installed 0.10.3
I get 3 warnings whenever i click the persistent dmg condition
`Error: You are accessing the NPCPF2e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    logCompatibilityWarning commons.js:1685
    _logV10CompatibilityWarning commons.js:6612
    get data commons.js:6512
    getTokenImages artbutton.js:239
    prepTokenHUD artbutton.js:283
    <anonymous> artbutton.js:390
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5112
    _render foundry.js:67812
    call_wrapped libWrapper-wrapper.js:507
    tokenHUDRender hud-changes.js:7
    call_wrapper libWrapper-wrapper.js:616
    _render#0 libWrapper-wrapper.js:189
    render foundry.js:5026
    _onEmbeddedDocumentChange foundry.js:16596
    _onEmbeddedDocumentChange main.bundle.js:1
    _onCreateEmbeddedDocuments foundry.js:16559
    _onUpdateTokenActor foundry.js:22310
    _onUpdate main.bundle.js:19
    callback foundry.js:12711
    documents foundry.js:12692
    _handleUpdateEmbeddedDocuments foundry.js:12692
    _updateEmbeddedDocuments foundry.js:12570
    update commons.js:6765
    updateDocuments commons.js:6120
    update commons.js:6217
    createActorEmbeddedDocuments foundry.js:22010
    _createEmbeddedDocuments foundry.js:12378
    create commons.js:6707
    createDocuments commons.js:6077
    createDocuments main.bundle.js:1
    createEmbeddedDocuments commons.js:6295
    _StatusEffects_setStatusValue main.bundle.js:1
    _StatusEffects_activateListeners main.bundle.js:1
    _StatusEffects_activateListeners main.bundle.js:1
    onRenderTokenHUD main.bundle.js:1
    listen main.bundle.js:19
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5112
    _render foundry.js:67812
    call_wrapped libWrapper-wrapper.js:507
    tokenHUDRender hud-changes.js:7
    call_wrapper libWrapper-wrapper.js:616
    _render#0 libWrapper-wrapper.js:189
    render foundry.js:5026
    _onEmbeddedDocumentChange foundry.js:16596
    _onEmbeddedDocumentChange main.bundle.js:1
    _onDeleteEmbeddedDocuments foundry.js:16575
    _onUpdateTokenActor foundry.js:22332
    _onUpdate main.bundle.js:19
    callback foundry.js:12711
    documents foundry.js:12692
    _handleUpdateEmbeddedDocuments foundry.js:12692
    _updateEmbeddedDocuments foundry.js:12570
    update commons.js:6765
    updateDocuments commons.js:6120
    update commons.js:6217
    deleteActorEmbeddedDocuments foundry.js:22088
    _deleteEmbeddedDocuments foundry.js:12753
    delete commons.js:6826
    deleteDocuments commons.js:6165
    deleteDocuments main.bundle.js:1
commons.js:1696:34
`
`Error: You are accessing TokenDocumentPF2e#img which has been migrated to TokenDocumentPF2e#texture.src
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    logCompatibilityWarning commons.js:1685
    _logDataFieldMigration commons.js:6601
    get commons.js:6565
    getTokenImages artbutton.js:240
    prepTokenHUD artbutton.js:283
    <anonymous> artbutton.js:390
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5112
    _render foundry.js:67812
    call_wrapped libWrapper-wrapper.js:507
    tokenHUDRender hud-changes.js:7
    call_wrapper libWrapper-wrapper.js:616
    _render#0 libWrapper-wrapper.js:189
    render foundry.js:5026
    _onEmbeddedDocumentChange foundry.js:16596
    _onEmbeddedDocumentChange main.bundle.js:1
    _onCreateEmbeddedDocuments foundry.js:16559
    _onUpdateTokenActor foundry.js:22310
    _onUpdate main.bundle.js:19
    callback foundry.js:12711
    documents foundry.js:12692
    _handleUpdateEmbeddedDocuments foundry.js:12692
    _updateEmbeddedDocuments foundry.js:12570
    update commons.js:6765
    updateDocuments commons.js:6120
    update commons.js:6217
    createActorEmbeddedDocuments foundry.js:22010
    _createEmbeddedDocuments foundry.js:12378
    create commons.js:6707
    createDocuments commons.js:6077
    createDocuments main.bundle.js:1
    createEmbeddedDocuments commons.js:6295
    _StatusEffects_setStatusValue main.bundle.js:1
    _StatusEffects_activateListeners main.bundle.js:1
    _StatusEffects_activateListeners main.bundle.js:1
    onRenderTokenHUD main.bundle.js:1
    listen main.bundle.js:19
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5112
    _render foundry.js:67812
    call_wrapped libWrapper-wrapper.js:507
    tokenHUDRender hud-changes.js:7
    call_wrapper libWrapper-wrapper.js:616
    _render#0 libWrapper-wrapper.js:189
    render foundry.js:5026
    _onEmbeddedDocumentChange foundry.js:16596
    _onEmbeddedDocumentChange main.bundle.js:1
    _onDeleteEmbeddedDocuments foundry.js:16575
    _onUpdateTokenActor foundry.js:22332
    _onUpdate main.bundle.js:19
    callback foundry.js:12711
    documents foundry.js:12692
    _handleUpdateEmbeddedDocuments foundry.js:12692
    _updateEmbeddedDocuments foundry.js:12570
    update commons.js:6765
    updateDocuments commons.js:6120
    update commons.js:6217
    deleteActorEmbeddedDocuments foundry.js:22088
    _deleteEmbeddedDocuments foundry.js:12753
    delete commons.js:6826
    deleteDocuments commons.js:6165
    deleteDocuments main.bundle.js:1
commons.js:1696:34
`
`Error: You are accessing the NPCPF2e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    logCompatibilityWarning commons.js:1685
    _logV10CompatibilityWarning commons.js:6612
    get data commons.js:6512
    prepTokenHUD token-hud-controller.js:31
    <anonymous> pf2e-inspire-courage.js:14
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5112
    _render foundry.js:67812
    call_wrapped libWrapper-wrapper.js:507
    tokenHUDRender hud-changes.js:7
    call_wrapper libWrapper-wrapper.js:616
    _render#0 libWrapper-wrapper.js:189
    render foundry.js:5026
    _onEmbeddedDocumentChange foundry.js:16596
    _onEmbeddedDocumentChange main.bundle.js:1
    _onCreateEmbeddedDocuments foundry.js:16559
    _onUpdateTokenActor foundry.js:22310
    _onUpdate main.bundle.js:19
    callback foundry.js:12711
    documents foundry.js:12692
    _handleUpdateEmbeddedDocuments foundry.js:12692
    _updateEmbeddedDocuments foundry.js:12570
    update commons.js:6765
    updateDocuments commons.js:6120
    update commons.js:6217
    createActorEmbeddedDocuments foundry.js:22010
    _createEmbeddedDocuments foundry.js:12378
    create commons.js:6707
    createDocuments commons.js:6077
    createDocuments main.bundle.js:1
    createEmbeddedDocuments commons.js:6295
    _StatusEffects_setStatusValue main.bundle.js:1
    _StatusEffects_activateListeners main.bundle.js:1
    _StatusEffects_activateListeners main.bundle.js:1
    onRenderTokenHUD main.bundle.js:1
    listen main.bundle.js:19
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5112
    _render foundry.js:67812
    call_wrapped libWrapper-wrapper.js:507
    tokenHUDRender hud-changes.js:7
    call_wrapper libWrapper-wrapper.js:616
    _render#0 libWrapper-wrapper.js:189
    render foundry.js:5026
    _onEmbeddedDocumentChange foundry.js:16596
    _onEmbeddedDocumentChange main.bundle.js:1
    _onDeleteEmbeddedDocuments foundry.js:16575
    _onUpdateTokenActor foundry.js:22332
    _onUpdate main.bundle.js:19
    callback foundry.js:12711
    documents foundry.js:12692
    _handleUpdateEmbeddedDocuments foundry.js:12692
    _updateEmbeddedDocuments foundry.js:12570
    update commons.js:6765
    updateDocuments commons.js:6120
    update commons.js:6217
    deleteActorEmbeddedDocuments foundry.js:22088
    _deleteEmbeddedDocuments foundry.js:12753
    delete commons.js:6826
    deleteDocuments commons.js:6165
    deleteDocuments main.bundle.js:1
commons.js:1696:34
`
i've no idea if these are related to this module specifically, but they always appear when i click the status/condition, which is when the dialogue box is supposed to appear

**Comment by CarlosFdez** [comment]
This looks to be an incompatibility with whatever you're using to get that condition hud. Can you identify what the module is and if turning it off changes it? If so, I'll try looking to see if there's anything I can do.

There's a macro to pop open the same dialog that the module provides in the meanwhile, at least.

**Comment by CarlosFdez** [comment]
This was a compatibility issue with Monk's Little Details, which *should* be fixed as of v0.10.4
